name: CI/CD. 
on:
  push:
    branches:
    - main
  #pull_request:
   # branches:
    #- master

jobs:
  dev-branch:
         runs-on: ubuntu-latest
# Mobile folder job.
         steps:
             - uses: actions/checkout@v2
             - uses: dorny/paths-filter@v2
               id: filter
               with:
                 filters: |
                   path:
                     - 'codes/**'
             - name: Setup Java
               if: steps.filter.outputs.path == 'true'
               run: echo "hello-world"
             - uses: dorny/paths-filter@v2
               id: filte
               with:
                 filtes: |
                   workflow:
                     - 'workflow'
             - name: run the workflow
               if: steps.filte.outputs.workflow == 'true'
               run: echo "hello from the workflow"
