name: pipeline

on:
    push:
        branches: ['master','developer']
        paths: 
           - 'build/**'
jobs:
  dev-branch:
        runs-on: ubuntu-latest
        if: contains('refs/heads/developer',github.ref)
        steps:
            - uses: actions/checkout@v2
              with:
                token : ${{secrets.ACCESS_TOKEN}}
                #submodules : true
            - name: Configure Credentials For Develop
              run: |
                    whoami
                    sudo echo 'mv build/js/vars_dev.js build/js/vars.js' #>> .add_variables.sh
                    
                    ls -al
                    pwd
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{secrets.AWS_DEFAULT_REGION }}
            - name: Copy files to the test website with the AWS CLI
              run: |
                    ls -al
                    pwd
                    echo "${{vars.S3_BUCKET_DEV}}
                    #aws s3 sync ./build s3://install.emporio.ai/dev    
                    aws s3 sync ${{vars.S3_SOURCE}} ${{vars.S3_BUCKET_DEV}}
