name: CI/CD
on:
  push:
    branches:
    - main
    paths:
      - 'codes/**'
      - 'lambda/**'

env:
  FOLDER: ${{ env.FOLDER.commit == "true" }}


jobs:
  dev-branch:
        runs-on: ubuntu-latest
        if: contains('refs/heads/main',github.ref)
        steps:
            - uses: actions/checkout@v2
              #with:
               # token : ${.ACCESS_TOKEN}}
                #submodules : true
            - name: rename the file
              if: env.FOLDER == 'codes'
              run: echo "Running tests for folder1"
              env:
               MY_VAR: "codes"
                  
            - name: configure aws credentials
              if: env.FOLDER == 'lambda'
              run: whoami
              env:
               MY_VAR: "lambda"
