name: CI/CD. 
on:
  push:
    branches:
    - main
  #pull_request:
   # branches:
    #- master

jobs:
  dev-branch:
         runs-on: ubuntu-latest
         outputs:
            output1: ${{ steps.bucket.outputs.path }}
            output2: ${{ steps.workflow.outputs }}
# Mobile folder job.
         steps:
             - uses: actions/checkout@v2
             - uses: dorny/paths-filter@v2
               id: bucket
               with:
                 filters: |
                   path:
                     - 'codes/**'
             - name: Setup Java
               if: steps.bucket.outputs.path == 'true'
               run: echo "hello-world"
             - uses: dorny/paths-filter@v2
               id: workflow
               with:
                 filters: |
                   workflow:
                     - 'workflow'
             - name: run the workflow
               if: steps.workflow.outputs.workflow == 'true'
               run: echo "hello from the workflow"
